version: '3.7'


services:
  app:
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /usr/src/app
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpw
      - MYSQL_HOST=localhost
      - MYSQL_PORT=6000
      - MYSQL_DATABASE=books-catalog
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - 5000:3000
    command: [ "npm", "start" ]

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 6000:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: books-catalog
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpw
