version: '3.7'


services:
  db:
    image: mysql:latest
    container_name: database
    network_mode: bridge
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data5/db:/var/lib/mysql"
    restart: always
    ports:
      - 6001:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: books-catalog
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpw


  app:
    image: node:latest
    container_name: books-catalog
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /usr/src/app
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpw
      - MYSQL_HOST=localhost
      - MYSQL_PORT=6001
      - MYSQL_DATABASE=books-catalog
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    command: npm start

